# Generated by Django 5.0.3 on 2024-09-05 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0006_user_is_faculty_staff_userfacultystaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_create_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_activity', models.ImageField(blank=True, null=True, upload_to='activity/')),
                ('activity_name', models.CharField(max_length=30)),
                ('activity_type', models.CharField(choices=[('1 ด้านวิชาการที่ส่งเสริมคุณลักษณะบัณฑิตที่พึงประสงค์', '1 ด้านวิชาการที่ส่งเสริมคุณลักษณะบัณฑิตที่พึงประสงค์'), ('2 ด้านกีฬาหรือการส่งเสริมสุขภาพ', '2 ด้านกีฬาหรือการส่งเสริมสุขภาพ'), ('3 ด้านบำเพ็ญประโยชน์หรือรักษาสิ่งแวดล้อม', '3 ด้านบำเพ็ญประโยชน์หรือรักษาสิ่งแวดล้อม'), ('4 ด้านเสริมสร้างคุณธรรมและจริยธรรม', '4 ด้านเสริมสร้างคุณธรรมและจริยธรรม'), ('5 ด้านส่งเสริมศิลปะและวัฒนธรรม', '5 ด้านส่งเสริมศิลปะและวัฒนธรรม'), ('6 ด้านกิจกรรมอื่นๆ', '6 ด้านกิจกรรมอื่นๆ')], max_length=100)),
                ('start_date_create_activity', models.DateTimeField()),
                ('due_date_create_activity', models.DateTimeField()),
                ('due_date_registration', models.DateTimeField()),
                ('place', models.CharField(max_length=30)),
                ('start_date_activity', models.DateTimeField()),
                ('due_date_activity', models.DateTimeField()),
                ('description', models.CharField(max_length=30)),
                ('credit', models.IntegerField(default=0)),
                ('max_participants', models.IntegerField()),
                ('registered_count', models.IntegerField(default=0)),
                ('is_registration_open', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_activity2', to='Accounts.userperson_responsible_for_the_project')),
            ],
        ),
        migrations.CreateModel(
            name='db_activity_adduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_activity_adduser2', to='Accounts.userstudent')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_activity_adduser2', to='ActivityParticipationManagementSystem.db_create_activity')),
            ],
            options={
                'unique_together': {('student', 'activity')},
            },
        ),
    ]
