# Generated by Django 5.1.3 on 2025-11-20 20:04

import ActivityParticipationManagementSystem.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_create_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_activity', models.ImageField(blank=True, null=True, upload_to=ActivityParticipationManagementSystem.models.upload_to_activity_img_activity)),
                ('activity_name', models.CharField(max_length=30)),
                ('activity_type', models.CharField(choices=[('1 ด้านวิชาการที่ส่งเสริมคุณลักษณะบัณฑิตที่พึงประสงค์', '1 ด้านวิชาการที่ส่งเสริมคุณลักษณะบัณฑิตที่พึงประสงค์'), ('2 ด้านกีฬาหรือการส่งเสริมสุขภาพ', '2 ด้านกีฬาหรือการส่งเสริมสุขภาพ'), ('3 ด้านบำเพ็ญประโยชน์หรือรักษาสิ่งแวดล้อม', '3 ด้านบำเพ็ญประโยชน์หรือรักษาสิ่งแวดล้อม'), ('4 ด้านเสริมสร้างคุณธรรมและจริยธรรม', '4 ด้านเสริมสร้างคุณธรรมและจริยธรรม'), ('5 ด้านส่งเสริมศิลปะและวัฒนธรรม', '5 ด้านส่งเสริมศิลปะและวัฒนธรรม'), ('6 ด้านกิจกรรมอื่นๆ', '6 ด้านกิจกรรมอื่นๆ')], max_length=100)),
                ('due_date_registration', models.DateTimeField()),
                ('description', models.CharField(max_length=30)),
                ('credit', models.IntegerField(default=0)),
                ('max_participants', models.IntegerField()),
                ('registered_count', models.IntegerField(default=0)),
                ('is_registration_open', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('announcement_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_days', models.IntegerField(default=1)),
                ('semester', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('academic_year', models.IntegerField(default=2568)),
                ('user_faculty_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_activity_faculty', to='Accounts.userfacultystaff')),
                ('user_person_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_activity_responsible', to='Accounts.userperson_responsible_for_the_project')),
            ],
        ),
        migrations.CreateModel(
            name='db_activity_adduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_activity_adduser2', to='Accounts.userstudent')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_activity_adduser2', to='ActivityParticipationManagementSystem.db_create_activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=ActivityParticipationManagementSystem.models.upload_to_activity_pdfs)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='ActivityParticipationManagementSystem.db_create_activity')),
            ],
        ),
        migrations.CreateModel(
            name='TimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('start_date_activity', models.DateTimeField()),
                ('due_date_activity', models.DateTimeField()),
                ('activity_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TimeEvent', to='ActivityParticipationManagementSystem.db_create_activity')),
            ],
        ),
    ]
