# Generated by Django 5.0.3 on 2024-09-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_create_activity',
            name='due_date_create_activity',
        ),
        migrations.RemoveField(
            model_name='db_create_activity',
            name='start_date_create_activity',
        ),
    ]
