# Generated by Django 5.0.3 on 2024-09-10 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0002_remove_db_create_activity_due_date_create_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='activity_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='ActivityParticipationManagementSystem.db_create_activity')),
            ],
        ),
    ]
