# Generated by Django 5.0.3 on 2024-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0003_activitypdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_create_activity',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
