# Generated by Django 5.0.3 on 2024-09-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0005_db_activity_adduser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_activity_adduser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
