# Generated by Django 5.1.3 on 2024-11-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0006_alter_db_activity_adduser_is_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='db_activity_adduser',
            unique_together=set(),
        ),
    ]
