# Generated by Django 5.1.3 on 2024-12-24 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0007_alter_db_activity_adduser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_create_activity',
            name='announcement_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_create_activity',
            name='semester',
            field=models.CharField(choices=[('1/2567', '1/2567'), ('2/2567', '2/2567'), ('ฤดูร้อน/2567', 'ฤดูร้อน/2567')], default='1/2567', max_length=20),
        ),
    ]
