# Generated by Django 5.1.3 on 2024-12-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0009_alter_db_create_activity_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_create_activity',
            name='semester',
            field=models.CharField(blank=True, choices=[], max_length=20),
        ),
    ]
