# Generated by Django 5.1.3 on 2025-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_user_is_faculty_staff_userfacultystaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacultystaff',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
